# Site settings
title: Welcome
email: siddgoyal@gmail.com
description: > Lo and behold !!
  Watch out for awesome stuff here # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sidgoyal.github.io" # the base hostname & protocol for your site
github_username: sidgoyal 

# Build settings
markdown: kramdown
