# Site settings
title: Welcome
email: siddgoyal@gmail.com
description:  Lo and behold !!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sidgoyal.github.io" # the base hostname & protocol for your site
github_username: sidgoyal 

# Build settings
markdown: kramdown
